export { default as CompTest } from './test'
// export { default as CheckboxItem } from './checkbox'
// export { default as ButtonItem } from './button'
// export { default as InputItem } from './input-item'
// export { default as InputNumber } from './input-number'
